### ISSUE TITLE
[ Question ] How will you release this as a mac app ?

### ISSUE THREAD

**Issue by sivrish** [PhilippMatthes/neural-greenscreen#2]
Will you be able to release your current project with node.js as an mac app ? and also why you haven't gone with coreml since the upcoming apple silicons are going to have ANE in them ? also sorry for using issues page for this.

**Comment by PhilippMatthes** [comment]
> Will you be able to release your current project with node.js as an mac app ?

This is currently not planned, and would involve some more research on my side on how to embed this into a single app. I see that the plugin in combination with TensorflowJS is kinda hacky and requires some time and experience to setup, but it works for my purpose. A better solution for me would be to improve the Readme to be more descriptive on how to setup the application. Maybe you could contribute on which points are missing? Or, firstly, did you encounter any problems setting it up?

>  and also why you haven't gone with coreml since the upcoming apple silicons are going to have ANE in them ? also sorry for using issues page for this.

Actually, my first try was using the pretrained DeepLabV3 Model from [Apple's ML models](https://developer.apple.com/machine-learning/models/) and the Vision framework. But the model didn't produce acceptable results in my environment, even though I tried several ways to pre-/post-process the data. So, before going with a full-on model conversion of the BodyPix net to Core ML I went with the micro service oriented approach. Currently, I don't plan on looking back into using another Core ML model, but maybe you could try this out and give me some feedback? If you need help with something, feel free to ask here.

**Comment by sivrish** [comment]
I don't have much expertise on macOS development. Just trying to create something similar to snap-camera mac app. Since your approach was not my idea for the app, I didn't tried it. But I'll be happy to help you with the CoreML part in which I've expertise in. I'll be able to help you convert the model to CoreML and I've seen so much performance improvement on running CoreML on iPhones rather than using libraries like TFLite, Libtorch or even OpenCV's DNN module. So I believe in CoreML.

I'm currently looking into XPC framework for IPC from my app to the DAL Plugin. Which I think will be easy to publish and have future support on the ARM Macs too ( I could be wrong ).

Anyway thanks for replying.
